- name: Create nginx logs folder
  become: true
  ansible.builtin.file:
    path: "{{ app_deploy_target | dirname }}/logs"
    state: directory
    owner: www-data
    mode: "0755"

- name: Upload nginx-fpm.sh
  become: true
  ansible.builtin.template:
    src: fpm.conf.j2
    dest: /etc/nginx/sites-enabled/{{ app_domain }}-fpm.conf
    mode: "0644"

- name: Upload nginx.conf
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ app_domain }}.conf
    mode: "0644"
