- name: Setup background worker
  ansible.builtin.include_tasks: worker.yml
  vars:
    zone_name: mq
  loop:
    - discussion
    - pr
    - progress
    - wbw.analyses
    - export.pali.chapter
    - export.article
    - ai.translate
  loop_control:
    loop_var: worker_name
