- name: Download source code
  ansible.builtin.unarchive:
    src: https://github.com/iapt-platform/mint/archive/{{ mint_version }}.zip
    dest: "{{ ansible_env.HOME }}/build"
    remote_src: true
    creates: "{{ ansible_env.HOME }}/build/mint-{{ mint_version }}"

- name: Install third packages
  ansible.builtin.command: docker/mint/run.sh {{ app_mint_image_name }} setup
  args:
    chdir: "{{ ansible_env.HOME }}/build/mint-{{ mint_version }}"
    creates: api-v8/public/node_modules

- name: Download repo
  ansible.builtin.fetch:
    src: "{{ ansible_env.HOME }}/build/mint-{{ mint_version }}"
    dest: "{{ playbook_dir }}/tmp/"
    mode: "0755"
# - name: Upload dashboard dist
#   ansible.builtin.copy:
#     src: "{{ playbook_dir }}/tmp/mint-{{ mint_version }}/dashboard-v4/dashboard/dist"
#     dest: "{{ ansible_env.HOME }}/build/mint-{{ mint_version }}/dashboard-v4/dashboard"
#     mode: "0755"

# - name: Compress repo.xz
#   community.general.archive:
#     path: "{{ ansible_env.HOME }}/build/mint-{{ mint_version }}"
#     dest: "{{ ansible_env.HOME }}/build/mint-{{ mint_version }}.tar.xz"
#     format: xz
#     mode: "0444"

