- name: Build frontend v4
  hosts: 127.0.0.1
  roles:
    - mint-dashboard-v4-build

- name: Setup mint repo
  hosts:
    - web
    - fpm
    - task
    - fort
  roles:
    - mint-v2.1

- name: Setup postgresql pali t-search
  hosts:
    - db
  tasks:
    - name: Upload pali.stop
      become: true
      ansible.builtin.copy:
        dest: "/usr/share/postgresql/{{ app_postgresql_version }}/tsearch_data/"
        src: "{{ playbook_dir }}/tsearch_data/pali.stop"
        owner: root
        group: root
        mode: "0444"
    - name: Upload pali.syn
      become: true
      ansible.builtin.copy:
        dest: "/usr/share/postgresql/{{ app_postgresql_version }}/tsearch_data/"
        src: "{{ playbook_dir }}/tsearch_data/pali.syn"
        owner: root
        group: root
        mode: "0444"
    - name: Restart postgresql server
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: postgresql

- name: Start mint background workers
  hosts:
    - task
  tasks:
    - name: Start worker service
      ansible.builtin.systemd_service:
        name: "{{ app_container_prefix }}-{{ app_domain }}-worker-mq-{{ item }}"
        enabled: true
        state: restarted
        scope: user
      loop:
        - discussion
        - pr
        - progress
        - wbw.analyses
        - export.pali.chapter
        - export.article
        - ai.translate

- name: Start mint php-fpm
  hosts:
    - fpm
  tasks:
    - name: Start fpm service
      ansible.builtin.systemd_service:
        name: "{{ app_container_prefix }}-{{ app_domain }}-fpm-{{ app_php_fpm_port }}"
        enabled: true
        state: restarted
        scope: user

- name: Setup nginx
  hosts:
    - web
  roles:
    - mint-nginx

- name: Start single-node worker
  hosts:
    - fort
  tasks:
    - name: Start schedule run service
      ansible.builtin.systemd_service:
        name: "{{ app_container_prefix }}-{{ app_domain }}-worker-{{ item }}"
        enabled: true
        state: restarted
        scope: user
      loop:
        - schedule-run
