- name: Build frontend v4
  hosts: 127.0.0.1
  roles:
    - mint-dashboard-v4-build

- name: Setup mint repo
  hosts:
    - web
    - fpm
    - task
    - fort
  roles:
    - mint-v2.1

- name: Setup postgresql pali t-search
  hosts:
    - db
  tasks:
    - name: Upload pali.stop
      become: true
      ansible.builtin.copy:
        dest: "/usr/share/postgresql/{{ app_postgresql_version }}/tsearch_data/"
        src: "{{ playbook_dir }}/tsearch_data/pali.stop"
        owner: root
        group: root
        mode: "0444"
    - name: Upload pali.syn
      become: true
      ansible.builtin.copy:
        dest: "/usr/share/postgresql/{{ app_postgresql_version }}/tsearch_data/"
        src: "{{ playbook_dir }}/tsearch_data/pali.syn"
        owner: root
        group: root
        mode: "0444"
    - name: Restart postgresql server
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: postgresql

- name: Setup mint background workers
  hosts:
    - task
  roles:
    - mint-workers

- name: Setup mint php-fpm
  hosts:
    - fpm
  roles:
    - mint-php-fpm

- name: Setup nginx
  hosts:
    - web
  roles:
    - mint-nginx
