- name: Upload .env(v2)
  ansible.builtin.template:
    src: v2/env.j2
    dest: "{{ app_deploy_target }}/api-v8/.env"
    mode: "0444"

- name: Upload config.php(v1)
  ansible.builtin.template:
    src: v1/config.php.j2
    dest: "{{ app_deploy_target }}/api-v8/public/app/config.php"
    mode: "0444"

- name: Upload config.js(v1)
  ansible.builtin.template:
    src: v1/config.js.j2
    dest: "{{ app_deploy_target }}/api-v8/public/app/config.js"
    mode: "0444"

- name: Upload vendors.sh
  ansible.builtin.template:
    src: containers/vendors.sh.j2
    dest: "{{ app_deploy_target }}/scripts/vendors.sh"
    mode: "0555"

- name: Initialize vendors and configuration
  containers.podman.podman_container:
    name: "{{ app_domain }}-initialize"
    image: "{{ app_mint_image_name }}"
    command: "{{ app_deploy_target }}/scripts/vendors.sh"
    volumes:
      - "{{ app_deploy_target }}:{{ app_deploy_target }}:z"
    workdir: "{{ app_deploy_target }}"
    # auto_remove: true

- name: Setup background worker
  ansible.builtin.include_tasks: workers.yml
  vars:
    zone_name: mq
  loop:
    - discussion
    - pr
    - progress
    - wbw.analyses
    - export.pali.chapter
    - export.article
    - ai.translate
  loop_control:
    loop_var: worker_name

- name: Setup schedule run
  ansible.builtin.import_tasks: schedule-run.yml

- name: Setup php-fpm
  ansible.builtin.import_tasks: php-fpm.yml

- name: Create a current link
  ansible.builtin.file:
    src: "{{ app_deploy_target }}"
    dest: "{{ app_deploy_target | dirname }}/current"
    state: link
