- name: Upload .env(v2)
  ansible.builtin.template:
    src: v2/env.j2
    dest: "{{ app_deploy_target }}/api-v8/.env"
    mode: "0444"

- name: Upload config.php(v1)
  ansible.builtin.template:
    src: v1/config.php.j2
    dest: "{{ app_deploy_target }}/api-v8/public/app/config.php"
    mode: "0444"

- name: Upload config.js(v1)
  ansible.builtin.template:
    src: v1/config.js.j2
    dest: "{{ app_deploy_target }}/api-v8/public/app/config.js"
    mode: "0444"

- name: Upload vendors.sh
  ansible.builtin.copy:
    src: vendors.sh
    dest: "{{ app_deploy_target }}/scripts/"
    mode: "0555"

- name: Initialize vendors and configuration
  containers.podman.podman_container:
    name: "{{ app_domain }}-initialize"
    image: "{{ app_mint_image_name }}"
    command: /srv/scripts/vendors.sh
    volumes:
      - "{{ app_deploy_target }}:/srv"
    auto_remove: true
