- name: Upload .env(v2)
  ansible.builtin.template:
    src: v2/env.j2
    dest: "{{ app_deploy_target }}/api-v8/.env"
    mode: "0444"

- name: Upload config.php(v1)
  ansible.builtin.template:
    src: v1/config.php.j2
    dest: "{{ app_deploy_target }}/api-v8/public/app/config.php"
    mode: "0444"

- name: Upload config.js(v1)
  ansible.builtin.template:
    src: v1/config.js.j2
    dest: "{{ app_deploy_target }}/api-v8/public/app/config.js"
    mode: "0444"

- name: Upload vendors.sh
  ansible.builtin.copy:
    src: vendors.sh
    dest: "{{ app_deploy_target }}/scripts/"
    mode: "0555"

- name: Initialize vendors and configuration
  containers.podman.podman_container:
    name: mint-initialize-vendors-configs
    image: "{{ app_mint_image_name }}"
    command: /srv/scripts/vendors.sh
    volumes:
      - "{{ app_deploy_target }}:/srv"
    auto_remove: true
# - name: Setup third packages
#   ansible.builtin.command:
#     argv:
#       - "{{ app_deploy_target }}/docker/mint/run.sh"
#       - "{{ app_mint_image_name }}"
#       - setup
#     chdir: "{{ app_deploy_target }}/"
#     creates: "{{ app_deploy_target }}/api-v8/public/node_modules"

# # https://laravel.com/docs/10.x/scheduling#running-the-scheduler
# - name: Upload scheduler service
#   become: true
#   ansible.builtin.template:
#     src: v2/scheduler.service.j2
#     dest: /usr/lib/systemd/system/scheduler.{{ app_domain }}.service
#     owner: root
#     group: root
#     mode: "0644"

# # https://wiki.archlinux.org/title/Systemd/Timers
# - name: Upload scheduler timer
#   become: true
#   ansible.builtin.template:
#     src: v2/scheduler.timer.j2
#     dest: /usr/lib/systemd/system/scheduler.{{ app_domain }}.timer
#     owner: root
#     group: root
#     mode: "0644"

# - name: Setup laravel queue workers
#   ansible.builtin.import_tasks: queue-workers.yml
# - name: Setup morus service
#   ansible.builtin.import_tasks: morus.yml

# - name: Setup lily service
#   ansible.builtin.import_tasks: lily.yml

# - name: Setup tulip service
#   ansible.builtin.import_tasks: tulip.yml
