- name: upload lily config.toml
  template:
    src: v2/lily/config.toml.j2
    dest: "{{ app_deploy_root }}/agile/rpc/lily/config.toml"
    mode: "0644"

- name: upload lily rpc server service
  become: true
  template:
    src: v2/lily/services/server.service.j2
    dest: /usr/lib/systemd/system/rpc.lily.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"

- name: upload lily rpc worker service
  become: true
  template:
    src: v2/lily/services/worker.service.j2
    dest: /usr/lib/systemd/system/worker.lily.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"
