- name: Create www folder
  become: true
  ansible.builtin.file:
    path: "/mnt/{{ app_domain }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Download source code
  ansible.builtin.unarchive:
    src: https://github.com/iapt-platform/mint/archive/{{ mint_version }}.zip
    dest: "/mnt/{{ app_domain }}"
    remote_src: true
    creates: "{{ app_deploy_target }}"

# - name: Upload shared
#   ansible.posix.synchronize:
#     src: "{{ playbook_dir }}/shared"
#     dest: "/mnt/{{ app_domain }}/shared"

- name: Upload dashboard-v4 dist
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/tmp/mint/dashboard-v4/dashboard/dist-{{ mint_version }}/"
    dest: "{{ app_deploy_target }}/dashboard-v4/dashboard/dist/"

- name: Setup laravel
  ansible.builtin.import_tasks: laravel-v8.yml

- name: Force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
