- name: upload {{ name }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ name }}.worker.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"
  vars:
    name: "discussion"

- name: upload {{ name }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ name }}.worker.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"
  vars:
    name: "pr"

- name: Upload {{ name }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ name }}.worker.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"
  vars:
    name: "progress"

- name: Upload {{ name }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ name }}.worker.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"
  vars:
    name: "wbw.analyses"

- name: upload {{ name }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ name }}.worker.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"
  vars:
    name: "export.pali.chapter"

- name: Upload {{ name }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ name }}.worker.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"
  vars:
    name: "export.article"

- name: Upload {{ name }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ name }}.worker.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"
  vars:
    name: "ai.translate"
