- name: Upload script for schedule-run
  ansible.builtin.copy:
    src: schedule-run.sh
    dest: "{{ app_deploy_target }}/scripts/worker-{{ zone_name }}-{{ worker_name }}.sh"
    mode: "0555"

- name: Stop schedule-run
  containers.podman.podman_container:
    name: "{{ app_domain }}-worker-schedule-run"
    state: absent

- name: Start schedule-run
  containers.podman.podman_container:
    name: "{{ app_domain }}-worker-schedule-run"
    image: "{{ app_mint_image_name }}"
    command: "{{ app_deploy_target }}/scripts/worker-schedule-run.sh"
    volumes:
      - "{{ app_deploy_target }}:{{ app_deploy_target }}:z"
    workdir: "{{ app_deploy_target }}"
    # auto_remove: true
    generate_systemd:
      path: "{{ app_deploy_target | dirname }}/systemd"
      container_prefix: mint
      names: true
      restart_policy: always
      stop_timeout: 120
# TODO timer
