- name: Install dbmate
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-{{ app_dbmate_arch }}"
    dest: /usr/local/bin/dbmate
    mode: "0555"
    creates: /usr/local/bin/dbmate

- name: Create the deployment folder
  become: true
  ansible.builtin.file:
    path: "{{ app_deploy_target }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Create the logs folder
  become: true
  ansible.builtin.file:
    path: "{{ app_deploy_target }}/logs"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "0755"

- name: Unarchive repo
  ansible.builtin.unarchive:
    src: https://github.com/iapt-platform/mint/archive/{{ mint_version }}.zip
    dest: "{{ app_deploy_target }}/mint"
    remote_src: true
    creates: "{{ app_deploy_target }}/mint"

- name: Setup dashboard
  ansible.builtin.import_tasks: antd-v4.yml
- name: Setup systemd services
  ansible.builtin.import_tasks: systemd.yml

# https://laravel.com/docs/10.x/scheduling#running-the-scheduler
- name: Upload scheduler service
  become: true
  ansible.builtin.template:
    src: v2/scheduler.service.j2
    dest: /usr/lib/systemd/system/scheduler.{{ app_domain }}.service
    owner: root
    group: root
    mode: "0644"

# https://wiki.archlinux.org/title/Systemd/Timers
- name: Upload scheduler timer
  become: true
  ansible.builtin.template:
    src: v2/scheduler.timer.j2
    dest: /usr/lib/systemd/system/scheduler.{{ app_domain }}.timer
    owner: root
    group: root
    mode: "0644"

- name: Setup laravel queue workers
  ansible.builtin.import_tasks: queue-workers.yml
- name: Setup morus service
  ansible.builtin.import_tasks: morus.yml

- name: Setup lily service
  ansible.builtin.import_tasks: lily.yml

- name: Setup tulip service
  ansible.builtin.import_tasks: tulip.yml
