- name: upload {{ action }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ inventory_hostname }}-{{ action }}-worker.service
    owner: root
    group: root
    mode: "0644"
  vars:
    action: "discussion"

- name: upload {{ action }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ inventory_hostname }}-{{ action }}-worker.service
    owner: root
    group: root
    mode: "0644"
  vars:
    action: "pr"

- name: Upload {{ action }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ inventory_hostname }}-{{ action }}-worker.service
    owner: root
    group: root
    mode: "0644"
  vars:
    action: "progress"

- name: Upload {{ action }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ inventory_hostname }}-{{ action }}-worker.service
    owner: root
    group: root
    mode: "0644"
  vars:
    action: "wbw.analyses"

- name: upload {{ action }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ inventory_hostname }}-{{ action }}-worker.service
    owner: root
    group: root
    mode: "0644"
  vars:
    action: "export.pali.chapter"

- name: upload {{ action }} worker service
  become: true
  template:
    src: v2/queue-worker.service.j2
    dest: /usr/lib/systemd/system/{{ inventory_hostname }}-{{ action }}-worker.service
    owner: root
    group: root
    mode: "0644"
  vars:
    action: "export.article"
