- name: Upload php-fpm.sh
  ansible.builtin.template:
    src: launch.sh.j2
    dest: "{{ app_deploy_target }}/scripts/php-fpm.sh"
    mode: "0555"

- name: Stop php-fpm worker
  containers.podman.podman_container:
    name: "{{ app_domain }}-fpm-{{ app_php_fpm_port }}"
    state: absent

- name: Start php-fpm worker
  containers.podman.podman_container:
    name: "{{ app_domain }}-fpm-{{ app_php_fpm_port }}"
    image: "{{ app_mint_image_name }}"
    command: "{{ app_deploy_target }}/scripts/php-fpm.sh"
    ports:
      - "0.0.0.0:{{ app_php_fpm_port }}:9000/tcp"
    volumes:
      - "{{ app_deploy_target }}:{{ app_deploy_target }}:z"
    workdir: "{{ app_deploy_target }}"
    # auto_remove: true
